### ISSUE TITLE
BUILD FAILED

### ISSUE THREAD

**Issue by ronlinet** [codenameone/PropertyCross#1]
All works fine in emulator but I cannot not generate the apk. 

```

    [javac] Note: /home/name/workspace-eclipse/List/src/com/propertycross/codename1/PropertyCross.java uses unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 100 errors

BUILD FAILED
/home/name/workspace-eclipse/List/build.xml:57: Compile failed; see the compiler error output for details.
```

**Comment by codenameone** [comment]
Can you post the full error log?

**Comment by ronlinet** [comment]
[logs.txt](https://github.com/codenameone/PropertyCross/files/847981/logs.txt)

**Comment by codenameone** [comment]
You need to have the libraries for Codename One in place. We don't commit the binaries to save space but you can copy them from a regular Codename One project created when doing `File->New Project`. Alternatively just do `File -> New Project -> Codename One -> Demos -> Property Cross`

**Comment by ronlinet** [comment]
My approach to use the PropertyCross was to create a new default Codename One project and copy the the PropertyCross files in to the project. So the default lib content was already there before I have tried to generate the Android .apk. Please check bellow the bellow terminal output.   
```
~/workspace-eclipse/List/lib$ ls 
CLDC11.jar  cloudinary-codenameone.cn1lib  CodenameOne.jar  CodenameOne_SRC.zip  impl

``` 
Is there anything else to be copied ?
Thank you for your time. 
PS: A standard cloning approach from git would be helpful.

**Comment by codenameone** [comment]
Fetching the binaries dynamically is problematic, see this post covering how to set up a project from git: https://www.codenameone.com/blog/tip-setup-codename-one-demo-from-git.html
